### PR TITLE
Base implementation embedders

### PR DESCRIPTION
**Pull request by SilvanHSLU**
- Deleted embedder.py as it's not necessary with the new concept
- Implemeted two specific embedder for tags and genres with checks to not generate empty embeddings.
- Implemented test notebook to ensure that the embeddings are as expected

### CODE REVIEW

**Comment by SilvanHSLU** [comment]
@V8-Luky game_data.py is not properly adjusted as either you or we together need to decide how to save/use the embedders now but the API is rn not adapted correctly. I'm aware of that.

**Review by V8-Luky — APPROVED** [review]
Looking good :)
Could you maybe add the newly used libraries to the requirements though?

**Comment by V8-Luky** [comment]
> @V8-Luky game_data.py is not properly adjusted as either you or we together need to decide how to save/use the embedders now but the API is rn not adapted correctly. I'm aware of that.

I'll see to it that I populate the database with both embeddings - I'll have a look then how multiple embedders should be included there.

**Comment by SilvanHSLU** [comment]
> Looking good :) Could you maybe add the newly used libraries to the requirements though?

Done!

**Pull request merged**
